feat: add documentation for Windows (WSL2) installation
instill-ai/instill-core pull request #1045
Opened 2024-07-18 11:33 UTC by namwoam

Because

- We want to add support `instill-core` on Windows.

This commit

- Provides documentation for installing `instill-core` on Windows through WSL2

2024-07-18 23:51 UTC, pinglin requested changes
Please change as requested to simplify wording. Thanks.

2024-07-18 23:51 UTC, pinglin commented on README.md
> +  (c) Install `cuda-toolkit` on WSL2 following [this tutorial from Nvidia](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl-2)
```suggestion
  - Install the lastest version of `yq` from the GitHub [Repository](https://github.com/mikefarah/yq), as the package `yq` is not installed on Ubuntu WSL2 by default
  
  - Install the latest version of Docker Desktop on Windows and enable the WSL2 integration following the [tutorial](https://docs.docker.com/desktop/wsl) by Docker
  
  - (optional) Install `cuda-toolkit` on WSL2 following the [tutorial](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl-2) by NVIDIA
```

2024-07-19 10:17 UTC, namwoam commented on README.md
> +  (c) Install `cuda-toolkit` on WSL2 following [this tutorial from Nvidia](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl-2)
Changed as requested.

2024-07-23 00:42 UTC, pinglin approved these changes
LGTM

2024-07-23 00:45 UTC, merged